[project]
name = "blue-backup"
dependencies = [
    "tomli; python_version<'3.11'",
    "paramiko",
]
requires-python = ">=3.8"

[tool.mypy]
files = ["blue-backup"]
strict = true

[tool.ruff]
include = ["blue-backup"]

[tool.ruff.lint]
select = ["ALL"]

ignore = [
    "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed
    "COM812",  # Trailing comma missing
    "D107",  # Missing docstring in __init__
    "DTZ011",  # `datetime.date.today()` used
    "EM101",  # Exception must not use a string literal, assign to variable first
    "EM102",  # Exception must not use an f-string literal, assign to variable first
    "ERA001",  # Found commented-out code
    "S603",  # `subprocess` call: check for execution of untrusted input
    "TCH003",  # Move standard library import `...` into a type-checking block
    "TRY003",  # Avoid specifying long messages outside the exception class
    "TRY301",  # Abstract `raise` to an inner function
]

pydocstyle.convention = "google"

[tool.pylint.message_control]
disable = [
    "too-many-instance-attributes",
    # Module name "blue-backup" doesn't conform to snake_case naming style
    "invalid-name",
    # Import "import paramiko" should be placed at the top of the module
    "wrong-import-position",
]
